# Generated by Django 4.2.13 on 2024-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_acct_branch',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_acct_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
