# Generated by Django 4.2.13 on 2024-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_bank_acct_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_acct_branch',
            field=models.CharField(blank=True, null=True, verbose_name='Bank account branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_acct_no',
            field=models.CharField(blank=True, null=True, verbose_name='Bank account no.'),
        ),
    ]
