# Generated by Django 4.2.13 on 2024-05-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('HF', 'Health Fund'), ('PF', 'Pension Fund')], default='HF', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_fund', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-type'],
                'indexes': [models.Index(fields=['-type'], name='contributio_type_11039f_idx')],
            },
        ),
    ]
