# Generated by Django 4.2.13 on 2024-05-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fund',
            new_name='Fund_type_8e1783_idx',
            old_name='contributio_type_11039f_idx',
        ),
        migrations.AlterModelTable(
            name='fund',
            table='Fund',
        ),
    ]
