# Generated by Django 4.2.13 on 2024-05-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_rename_contributio_type_11039f_idx_fund_type_8e1783_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fund',
            new_name='fund_type_18302e_idx',
            old_name='Fund_type_8e1783_idx',
        ),
        migrations.AlterModelTable(
            name='fund',
            table='fund',
        ),
    ]
