# Generated by Django 4.2.13 on 2024-05-17 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0003_rename_fund_type_8e1783_idx_fund_type_18302e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_withdrawal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal',
            },
        ),
    ]
