# Generated by Django 4.2.13 on 2024-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0004_alter_fund_created_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='title',
            new_name='narration',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='title',
            new_name='narration',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='created',
            new_name='when',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='type',
            field=models.CharField(choices=[('HF', 'Health Fund'), ('PF', 'Pension Fund')], default='HF', max_length=2),
        ),
    ]
