# Generated by Django 4.2.13 on 2024-05-18 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0005_rename_title_fund_narration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50)),
                ('next_of_kin_fname', models.CharField(max_length=50)),
                ('next_of_kin_lname', models.CharField(max_length=50)),
                ('next_of_kin_telephone', models.CharField(max_length=50)),
                ('next_of_kin_address', models.TextField(blank=True, max_length=200)),
                ('next_of_kin_perc', models.CharField(max_length=3)),
                ('next_of_kin_city', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
