# Generated by Django 4.2.13 on 2024-05-18 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0006_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_fname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_lname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_perc',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_of_kin_telephone',
        ),
        migrations.AlterField(
            model_name='fund',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('telephone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=20)),
                ('perc', models.CharField(max_length=3, verbose_name='Percentage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
