# Generated by Django 4.2.13 on 2024-05-18 09:26

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0007_remove_member_next_of_kin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
