# Generated by Django 4.2.13 on 2024-05-18 09:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0008_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
