# Generated by Django 4.2.13 on 2024-05-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0010_alter_member_photo_alter_nextofkin_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='member',
            new_name='to_member',
        ),
    ]
