# Generated by Django 4.2.13 on 2024-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0012_member_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
