# Generated by Django 4.2.13 on 2024-05-21 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0015_alter_nextofkin_to_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('HF', 'Health Fund'), ('PF', 'Pension Fund')], default='HF', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings',
                'ordering': ['-type'],
            },
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.AddIndex(
            model_name='savings',
            index=models.Index(fields=['-type'], name='savings_type_67c85d_idx'),
        ),
    ]
