# Generated by Django 4.2.13 on 2024-05-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0017_alter_savings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextofkin',
            options={'ordering': ['-perc']},
        ),
        migrations.AlterModelTable(
            name='nextofkin',
            table='nextofkin',
        ),
    ]
