# Generated by Django 4.2.13 on 2024-05-23 17:00

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0018_alter_nextofkin_options_alter_nextofkin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='kins/%Y/%m/%d/'),
        ),
    ]
