# Generated by Django 4.2.13 on 2024-05-24 05:43

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0020_nextofkin_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='perc',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='kins/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
