# Generated by Django 4.2.13 on 2024-05-24 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0021_alter_nextofkin_perc_alter_nextofkin_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
