# Generated by Django 4.2.13 on 2024-05-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0023_nextofkin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='savings',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='savings_withdrawal', to='contribution.savings'),
            preserve_default=False,
        ),
    ]
