# Generated by Django 4.2.13 on 2024-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0024_withdrawal_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='savings',
        ),
    ]
