# Generated by Django 4.2.13 on 2024-05-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0026_alter_savings_amount_alter_withdrawal_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='when',
            new_name='withdrawn',
        ),
    ]
