# Generated by Django 4.2.13 on 2024-05-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0028_alter_nextofkin_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_next_of_kin', to=settings.AUTH_USER_MODEL),
        ),
    ]
