# Generated by Django 4.2 on 2024-05-31 09:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribution', '0029_alter_nextofkin_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='perc',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Percentage'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maturity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this investment still active?')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest', models.DecimalField(blank=True, decimal_places=2, help_text='Interest earned on investment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trader', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment',
                'ordering': ['-created'],
            },
        ),
    ]
