# Generated by Django 4.2 on 2024-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0030_alter_nextofkin_perc_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created',
            field=models.DateTimeField(verbose_name='Date of investment (yyyy-mm-dd)'),
        ),
    ]
