# Generated by Django 5.0.6 on 2024-06-01 18:18

import datetime
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0031_alter_investment_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='member',
        ),
        migrations.AddField(
            model_name='investment',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 18, 18, 20, 279224, tzinfo=datetime.timezone.utc), help_text='Day of maturity'),
        ),
        migrations.AddField(
            model_name='investment',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='investments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount invested', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start of transaction'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='maturity',
            field=models.IntegerField(default=0, help_text='When does it mature?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate at the time of transaction', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
