# Generated by Django 5.0.6 on 2024-06-01 19:46

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0033_alter_investment_ended_alter_investment_maturity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 19, 46, 42, 509998, tzinfo=datetime.timezone.utc), help_text='Day of maturity'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='investments_made', to=settings.AUTH_USER_MODEL, verbose_name='contributors'),
        ),
    ]
